=== nti-de/SAGisALKISSearch/resources/config/GenericDialog/Configuration/SAGisGnDlgConfig.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="SAGisGnDlgConfig">
		<xs:complexType>
			<xs:sequence>

				<xs:element name="Container" minOccurs="1" maxOccurs="1">
					<xs:complexType>
						<xs:sequence>
							<!-- <xs:element type="xs:string" name="Class" minOccurs="1" maxOccurs="1"/> -->
							<xs:element type="xs:string" name="Caption" minOccurs="1" maxOccurs="1"/>
							<xs:element type="xs:string" name="CssFiles" minOccurs="0" maxOccurs="1"/>
							<xs:element type="xs:string" name="SchemaNamePlaceHolder" minOccurs="0" maxOccurs="1" default="{SCHEMA_NAME_PLACEHOLDER}"/>
							<xs:element type="xs:string" name="SchemaName" minOccurs="0" maxOccurs="1"/>
							<xs:element name="ActivityLog" minOccurs="0" maxOccurs="1">
								<xs:complexType>
									<xs:attribute type="xs:boolean" default="false" name="Active" use="optional"/>
									<xs:attribute type="xs:string" name="InfoLogColumn" use="optional"/>
								</xs:complexType>
							</xs:element>
							
							<xs:element name="SearchTemplate">
								<xs:complexType mixed="true">
									<xs:sequence>
										<xs:element name="Queries" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Query" minOccurs="0" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element type="xs:string" name="BindTo" minOccurs="1" maxOccurs="1"/>
																<xs:element type="xs:string" name="Sql" minOccurs="1" maxOccurs="1"/>
																<xs:element type="xs:string" default="KEY" name="KeyValueField" minOccurs="0" maxOccurs="1" />
																<xs:element type="xs:string" default="CAPTION" name="CaptionValueField" minOccurs="0" maxOccurs="1" />
																<xs:element type="xs:string" default="{1} ({0})" name="CaptionFormat" minOccurs="0" maxOccurs="1" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Search" minOccurs="1" maxOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element type="xs:string" name="Sql" minOccurs="1" maxOccurs="1"/>
													<xs:element type="xs:string" name="FixedSqlWhere" minOccurs="0" maxOccurs="1" />

													<xs:element name="Parameter" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<!--<xs:attribute type="xs:string" default="" name="DataType" use="optional"/>-->
																	<xs:attribute type="xs:string" name="DbField" use="required"/>
																	<xs:attribute type="xs:string" name="FormField" use="required"/>
																	<xs:attribute type="xs:string" default="" name="DbJoinedTableName" use="optional"/>
																	<xs:attribute type="xs:string" default="" name="DbTableAlias" use="optional"/>
																	<xs:attribute type="xs:string" default="" name="DefaultValue" use="optional"/>
																	<xs:attribute type="xs:boolean" default="true" name="CaseSensitive" use="optional"/>
																	<xs:attribute type="xs:boolean" default="false" name="Range" use="optional"/>
																	<!--
																	<xs:attribute type="xs:boolean" default="true" name="Like" use="optional"/>
																	<xs:attribute type="xs:boolean" default="true" name="In" use="optional"/>
																	-->
																	<xs:attribute name="WhereCondition" default="IsEqual" use="optional">
																		<xs:simpleType>
																			<xs:restriction base="xs:string">
																				<xs:enumeration value="In"/>
																				<xs:enumeration value="Like"/>
																				<xs:enumeration value="IsEqual"/>
																			</xs:restriction>
																		</xs:simpleType>
																	</xs:attribute>
																	
																	<xs:attribute type="xs:string" default="AND" name="SqlOperator" use="optional"/>
																	<xs:attribute type="xs:string" default="String" name="DbFieldMgPropertyType" use="optional"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										
										<xs:element type="xs:string" name="SearchTemplate" maxOccurs="1" minOccurs="1" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							
							<xs:element name="InfoTemplate">
								<xs:complexType>
									<xs:sequence>
										<xs:element type="xs:boolean" default="true" name="Editable" minOccurs="0" maxOccurs="1"/>
										<xs:element name="Panels">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Panel" maxOccurs="unbounded" minOccurs="0">
														<xs:complexType>
															<xs:sequence>
																<xs:element type="xs:string" name="Caption"/>
																<xs:element type="xs:string" name="Authorisation" minOccurs="0" maxOccurs="1"/>
																<xs:element type="xs:boolean" default="true" name="Active" minOccurs="0" maxOccurs="1"/>
																<xs:element type="xs:boolean" default="false" name="HideIfQueryIsEmpty" minOccurs="0" maxOccurs="1"/>
																<xs:element type="xs:boolean" default="true" name="ShowDatacount" minOccurs="0" maxOccurs="1"/>
																<xs:element type="xs:integer" name="height" minOccurs="0" maxOccurs="1" default="600" />
																<xs:element name="Query">
																	<xs:complexType>
																		<xs:sequence>
																			
																			<xs:element type="xs:string" name="Name" minOccurs="0" maxOccurs="1" />
																			<xs:element type="xs:boolean" name="AllowEmpty" minOccurs="0" maxOccurs="1" default="true" />
																			<xs:element type="xs:integer" name="AllowMaxResults" minOccurs="0" maxOccurs="1" />
																			<xs:element type="xs:string" name="Parent" minOccurs="0" maxOccurs="1" />
																			<xs:choice>
																				<xs:element type="xs:string" name="Sql" minOccurs="1" maxOccurs="1" />
																				<xs:element name="Intersection" minOccurs="1" maxOccurs="1" >
																					<xs:complexType>
																						<xs:sequence>
																							<xs:element type="xs:string" name="TargetFeatureClass" minOccurs="0" maxOccurs="1" />
																							<xs:element type="xs:string" name="OrderBy" minOccurs="0" maxOccurs="1"/>
																							<xs:element type="xs:string" name="Filter" minOccurs="0" maxOccurs="1"/>
																							<xs:element type="xs:integer" name="MgFeatureSpatialOperation" minOccurs="0" maxOccurs="1" default="-1"/>
																							<xs:element type="xs:string" name="Property" minOccurs="0" maxOccurs="unbounded"/>
																							
																							<xs:element name="Translation" maxOccurs="unbounded" minOccurs="0">
																								<xs:complexType>
																									<xs:sequence>
																										<xs:element type="xs:string" name="Sql" minOccurs="1" maxOccurs="1" />
																										<xs:element type="xs:string" name="FromColumn" minOccurs="1" maxOccurs="1" />
																										<xs:element type="xs:string" name="ValueColumn" minOccurs="1" maxOccurs="1" />
																										<xs:element type="xs:string" name="IdColumn" minOccurs="1" maxOccurs="1" />
																									</xs:sequence>
																								</xs:complexType>
																							</xs:element>
																						</xs:sequence>
																					</xs:complexType>
																				</xs:element>
																			</xs:choice>
																			
																			<xs:element name="ShowInMap" minOccurs="0" maxOccurs="1" >
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element type="xs:string" name="LayerFeatureClassName" minOccurs="1" maxOccurs="1" />
																						<xs:element type="xs:string" name="BindTo" minOccurs="1" maxOccurs="1"/>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																			
																			
																		</xs:sequence>
																		<xs:attribute type="xs:string" name="JsDataColumns" />
																	</xs:complexType>
																</xs:element>

																<xs:element name="Bindings" maxOccurs="unbounded" minOccurs="0">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element type="xs:boolean" default="true" name="Active" minOccurs="0" maxOccurs="1"/>
																			<xs:element type="xs:string" name="Caption" minOccurs="0" maxOccurs="1" />
																			<xs:element type="xs:string" name="Sql" minOccurs="1" maxOccurs="1" />
																			<xs:element type="xs:string" name="BindTo" minOccurs="1" maxOccurs="1"/>
																			<xs:element type="xs:string" name="Authorisation" minOccurs="0" maxOccurs="1"/>
																			<xs:element name="HeaderText" maxOccurs="unbounded" minOccurs="0">
																				<xs:complexType>
																					<xs:simpleContent>
																						<xs:extension base="xs:string">
																							<xs:attribute type="xs:string" name="From" use="required"/>
																							<xs:attribute type="xs:string" name="To" use="required"/>
																						</xs:extension>
																					</xs:simpleContent>
																				</xs:complexType>
																			</xs:element>
																			<xs:element type="xs:boolean" name="ShowHeaderWhenEmpty" minOccurs="0" maxOccurs="1" default="false" />
																			
																			<xs:element name="JavaScriptClick" maxOccurs="unbounded" minOccurs="0">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element type="xs:string" name="Column" minOccurs="1" maxOccurs="1" />
																						<xs:element type="xs:string" name="JsFn" minOccurs="1" maxOccurs="1" />
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>

																<xs:choice>
																	<xs:element type="xs:string" name="ItemTemplate" maxOccurs="1" minOccurs="1" />

																	<xs:element name="NoItemTemplate" maxOccurs="1" minOccurs="1" >
																		<xs:complexType>
																			<xs:sequence>
																				<xs:element name="ColumnNameTranslation" maxOccurs="unbounded" minOccurs="0">
																					<xs:complexType>
																						<xs:simpleContent>
																							<xs:extension base="xs:string">
																								<xs:attribute type="xs:string" name="From" use="required"/>
																								<xs:attribute type="xs:string" name="To" use="required"/>
																							</xs:extension>
																						</xs:simpleContent>
																					</xs:complexType>
																				</xs:element>
																			</xs:sequence>
																		</xs:complexType>
																	</xs:element>
																	
																</xs:choice>

																<xs:element type="xs:string" name="FooterTemplate" maxOccurs="1" minOccurs="0" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>



			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== nti-de/SAGisALKISSearch/resources/config/GenericDialog/Configuration/AX_FLURSTUECK_SQLITE.xml
<?xml version="1.0" encoding="utf-8" ?>

<SAGisGnDlgConfig xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xsi:noNamespaceSchemaLocation="SAGisGnDlgConfig.xsd">
	<!--
	AX_FLURSTUECK - Flurstück
	Für SAGis ALKIS SQLite-DB
	Berechtigungen:
		AX_FLURSTUECK
		AX_PERSON
		AX_BUCHUNGSBLATT
		AX_LAGEBEZEICHNUNGMITHNR,AX_LAGEBEZEICHNUNGOHNEHNR
	-->
	<Container>
		<Caption>Flurstück</Caption>

		<SearchTemplate>
			<Queries>
				<Query>
					<BindTo>GEMARKUNG</BindTo>
					<Sql><![CDATA[
						SELECT a.FID, a.SCHLUESSEL, a.BEZEICHNUNG , count(b.FID) AS NUM
						FROM AX_GEMARKUNG a
							LEFT JOIN AX_FLURSTUECK b ON (b.GEMARKUNG = a.SCHLUESSEL)
						GROUP BY a.FID, a.SCHLUESSEL, a.BEZEICHNUNG
						HAVING count(b.FID) > 0
						ORDER BY a.BEZEICHNUNG ASC
					]]></Sql>

					<KeyValueField>SCHLUESSEL</KeyValueField>
					<CaptionValueField>BEZEICHNUNG</CaptionValueField>
				</Query>

				<Query>
					<BindTo>EX_NUTZUNGART_TBD</BindTo>
					<Sql><![CDATA[
						SELECT a.VALUE, a.SHORT_VALUE, count(1)
						FROM ex_nutzungart_tbd a
							INNER JOIN EX_FSTNUTZUNG b ON ( b.art_tabelle = a.short_value)
						GROUP BY a.value, a.short_value
						ORDER BY a.value asc
					]]></Sql>

					<KeyValueField>SHORT_VALUE</KeyValueField>
					<CaptionValueField>VALUE</CaptionValueField>
				</Query>

			</Queries>

			<Search>
				<Sql><![CDATA[
					SELECT DISTINCT(AX_FLURSTUECK.FID), AX_FLURSTUECK.FLURSTUECKSKENNZEICHEN
					FROM AX_FLURSTUECK
						LEFT JOIN EX_FSTNUTZUNG b ON ( b.FLURSTUECKSKENNZEICHEN = AX_FLURSTUECK.FLURSTUECKSKENNZEICHEN )
					{WHERE_PARAMETERS}
					ORDER BY AX_FLURSTUECK.FLURSTUECKSKENNZEICHEN ASC
				]]></Sql>

				<FixedSqlWhere>AX_FLURSTUECK.LZE is NULL</FixedSqlWhere>

				<Parameter DbField="GEMARKUNG" FormField="GEMARKUNG" />
				<Parameter DbField="FLURNUMMER" FormField="FLURNUMMER"/>
				<Parameter DbField="FLURSTUECKSNUMMER_ZAEHLER" FormField="FLURSTUECKSNUMMER_ZAEHLER" WhereCondition="Like" />
				<Parameter DbField="AMTLICHEFLAECHE" FormField="AMTLICHEFLAECHE" Range="true"/>
				<Parameter DbField="AREA" FormField="AREA" Range="true"/>
				<Parameter DbField="ART_TABELLE" DbJoinedTableName="EX_FSTNUTZUNG" DbTableAlias="b" FormField="EX_NUTZUNGART_TBD" />
			</Search>

			<SearchTemplate>SearchTemplates\AX_FLURSTUECK\AX_FLURSTUECK</SearchTemplate>
		</SearchTemplate>

		<InfoTemplate>
			<Panels>
				<!-- Allgemein, Flurstück - AX_FLURSTUECK -->
				<Panel>
					<Caption>Allgemein</Caption>
					<Authorisation>AX_FLURSTUECK</Authorisation>
					<ShowDatacount>false</ShowDatacount>
					<Query JsDataColumns = "FLURSTUECKSKENNZEICHEN">
						<Name>AX_FLURSTUECK</Name>
						<AllowEmpty>false</AllowEmpty>
						<AllowMaxResults>1</AllowMaxResults>
						<Sql><![CDATA[
								SELECT a.ID, a.FID, a.GEMEINDEZUGEHOERIGKEIT, a.ZEITPUNKTDERENTSTEHUNG, a.GEMARKUNG,
								 a.AMTLICHEFLAECHE, a.FLURNUMMER, a.FLURSTUECKSNUMMER_ZAEHLER, a.FLURSTUECKSNUMMER_NENNER,
								 a.FLURSTUECKSKENNZEICHEN, a.AREA, a.FLURSTUECKSFOLGE, a.ZUSTAENDIGESTELLE, a.ANLASS1, a.ANLASS2,

								 a.RECHTSBEHELFSVERFAHREN,
								 CASE WHEN a.RECHTSBEHELFSVERFAHREN = '0' THEN 'Nein' WHEN a.RECHTSBEHELFSVERFAHREN = '1' THEN 'Ja'  ELSE 'Keine Angabe' END as XRECHTSBEHELFSVERFAHREN,

								 a.ABWEICHENDERRECHTSZUSTAND,
								 CASE WHEN a.ABWEICHENDERRECHTSZUSTAND = '0' THEN 'Nein' WHEN a.ABWEICHENDERRECHTSZUSTAND = '1' THEN 'Ja'  ELSE 'Keine Angabe' END as XABWEICHENDERRECHTSZUSTAND,

								 a.ZWEIFELHAFTERFLURSTUECKSNA,
								 CASE WHEN a.ZWEIFELHAFTERFLURSTUECKSNA = '0' THEN 'Nein' WHEN a.ZWEIFELHAFTERFLURSTUECKSNA = '1' THEN 'Ja'  ELSE 'Keine Angabe' END as XZWEIFELHAFTERFLURSTUECKSNA,

								 ROUND(ABS(100 - (100 * a.AMTLICHEFLAECHE / a.AREA)), 3) as X_AREA_DIFF_PERC,

								 b.SCHLUESSELGESAMT as GEMEINDESCHLUESSEL, b.BEZEICHNUNG as GEMEINDEBEZEICHNUNG,
								 c.SCHLUESSELGESAMT as GEMARKUNGSCHLUESSEL, c.BEZEICHNUNG as GEMARKUNGBEZEICHNUNG,
								 d.BEZEICHNUNG as ZUSTAENDIGESTELLEBEZ,
								 e.VALUE AS ANLASS1_VALUE, f.VALUE AS ANLASS2_VALUE
								FROM AX_FLURSTUECK a
								 LEFT OUTER JOIN AX_GEMEINDE b ON ( b.GEMEINDEKENNZEICHEN = a.GEMEINDEZUGEHOERIGKEIT AND b.LZE is NULL )
								 LEFT OUTER JOIN AX_GEMARKUNG c ON ( c.SCHLUESSEL = a.GEMARKUNG AND c.LZE is NULL )
								 LEFT OUTER JOIN AX_DIENSTSTELLE d ON ( d.SCHLUESSEL = a.ZUSTAENDIGESTELLE AND d.LZE is NULL )
								 LEFT OUTER JOIN AA_ANLASSART_TBD e ON ( e.SHORT_VALUE = a.ANLASS1 )
								 LEFT OUTER JOIN AA_ANLASSART_TBD f ON ( f.SHORT_VALUE = a.ANLASS2 )
								WHERE a.FID = {SELECTED_MAP_ITEM} AND a.LZE is NULL
						]]></Sql>
					</Query>

					<Bindings>
						<Sql><![CDATA[
							SELECT
								e.BUCHUNGSBLATTKENNZEICHEN,
								d.VALUE as BUCHUNGSART_VALUE,
								b.VALUE as EIGENTUEMERART_VALUE,
								,(coalesce(c.VALUE, '') || ' ' ||
								coalesce(pe.VORNAME, '') || ' ' ||
								coalesce(pe.NACHNAMEODERFIRMA, '')) AS person_anrede_text
							FROM me_fs_pe me
								LEFT OUTER JOIN AX_BUCHUNGSBLATT e ON ( e.ID = me.BBID )
								LEFT OUTER JOIN AX_BUCHUNGSART_TBD d ON ( d.SHORT_VALUE = me.I_BUART )
								LEFT OUTER JOIN AX_EIGENTUEMERART_TBD b ON ( b.SHORT_VALUE = me.EIGENTUEMERART )
								LEFT JOIN ax_person pe ON pe.id = me.peid AND pe.lze IS NULL
								LEFT OUTER JOIN AX_ANREDE_PERSON_TBD c ON ( c.SHORT_VALUE = pe.ANREDE )
							WHERE
								me.I_BUART != '5000' AND
								me.fsid = '{ID}'
							ORDER BY pe.NACHNAMEODERFIRMA
					   ]]></Sql>
					   <BindTo>dataV_EIGENTUEMER_DIST_OVERVIEW</BindTo>
					   <HeaderText From="BUCHUNGSART_VALUE" To="Buchungsart"/>
					   <HeaderText From="EIGENTUEMERART_VALUE" To="Eigentümerart"/>
					   <HeaderText From="person_anrede_text" To="Eigentümer"/>
					   <HeaderText From="BUCHUNGSBLATTKENNZEICHEN" To="Buchungsblatt"/>
					</Bindings>

					<!-- Nutzung -->
					<Bindings>
						<Caption>Nutzung</Caption>
						<Sql><![CDATA[

							SELECT
								a.NUTZ_ID, a.FST_ID, a.AREA AS X_AREA_INTERSECTION,
								ROUND(((AX_FLURSTUECK.AMTLICHEFLAECHE * a.FLAECHEANTEIL) / 100)) as TFL_AMTLICH,
								100 * (ROUND(((AX_FLURSTUECK.AMTLICHEFLAECHE * a.FLAECHEANTEIL) / 100))) / AMTLICHEFLAECHE AS AMTL_FLAECHEANTEIL,
								a.FLAECHEANTEIL,
								AX_FLURSTUECK.AMTLICHEFLAECHE,
								AX_FLURSTUECK.AREA AS X_AREA_SOURCE,
								b.VALUE AS X_SUBTYPE_VALUE,
								c.VALUE AS ART_TABELLE_TEXT
							FROM AX_FLURSTUECK
								LEFT JOIN EX_FSTNUTZUNG a ON(a.FST_ID = AX_FLURSTUECK.ID)
								LEFT JOIN EX_NUTZUNGART_TBD c ON(c.SHORT_VALUE = a.ART_TABELLE)
								LEFT JOIN EX_TATSAECHLICHENUTZUNG ex_nutz ON ex_nutz.ID = a.NUTZ_ID
								LEFT JOIN EX_NUTZUNG_EX_TBD b ON(b.SHORT_VALUE = ex_nutz.FUNKTION)
							WHERE
								AX_FLURSTUECK.ID = '{ID}'
							ORDER BY a.AREA desc
						]]></Sql>

						<BindTo>data_gvNutzung</BindTo>

						<HeaderText From="ART_TABELLE_TEXT" To="Nutzungsart"/>
						<HeaderText From="X_SUBTYPE_VALUE" To="Unterart"/>
						<HeaderText From="X_AREA_INTERSECTION" To="Schnittfläche [m²]"/>
						<HeaderText From="FLAECHEANTEIL" To="Anteil in %"/>

						<JavaScriptClick>
							<Column>objektart_name</Column>
							<JsFn><![CDATA[
								zoomToFilter({layerName : 'sg_nutzung_f', filter : 'objectid = %gid%', doZoom : false}); return false;
								/*zoomToFilter({layerName : 'tg_nutzung', filter : 'gid = %gid%', doZoom : false}); return false;*/
							]]></JsFn>
						 </JavaScriptClick>
					</Bindings>


					<ItemTemplate>ItemTemplates\AX_FLURSTUECK\AX_FLURSTUECK</ItemTemplate>
				</Panel>



				<!--
				Buchungsstellen/-blätter
				Buchungsblätter des Flurstücks
				-->
				<Panel>
					<Caption>Buchungsstellen/-blätter</Caption>
					<Authorisation>AX_BUCHUNGSBLATT</Authorisation>
					<Query>
						<Name>V_BUCHUNGSBLATT_FS</Name>
						<Parent>AX_FLURSTUECK</Parent>

						<Sql><![CDATA[

								SELECT
									Distinct(me.I_BSID) AS BSID
									, bs.LAUFENDENUMMER
									, bs.ANTEIL_ZAEHLER
									, bs.ANTEIL_NENNER
									, bs.LZB
									, bs.buchungsart
									, tbdBuchungsArt.VALUE as buchungsart_VALUE
								FROM me_fs_bb me
									LEFT JOIN ax_buchungsstelle bs on (bs.LZE is null and me.I_BSID = bs.ID)
									LEFT JOIN ax_buchungsart_tbd tbdBuchungsArt on(tbdBuchungsArt.SHORT_VALUE = bs.buchungsart)
								WHERE me.FSID = '{ID}'
								ORDER BY bs.LAUFENDENUMMER
						]]></Sql>

					</Query>

					<Bindings>
						<Sql><![CDATA[

							SELECT
								bb.BUCHUNGSBLATTKENNZEICHEN,
								(bbBezirk.SCHLUESSELGESAMT || '/' || bbBezirk.BEZEICHNUNG) as BB_BEZIRK_SCHL_VALUE,
								bb.BUCHUNGSBLATTNUMMERMITBUCH,
								bb.BLATTART,
								bbBezirk.SCHLUESSELGESAMT as BB_BEZIRK_KEY,
								bbBezirk.BEZEICHNUNG as BB_BEZIRK_VALUE,

								tbdBlattart.VALUE as BLATTART_VALUE,
								(bb.BLATTART || '/' || tbdBlattart.VALUE) as BLATTART_SCHL_VALUE
							FROM me_bs_bb me
							 LEFT JOIN ax_buchungsblatt bb on (bb.LZE is null and bb.id = me.BBID)
							 LEFT OUTER JOIN AX_BUCHUNGSBLATTBEZIRK bbBezirk ON (bbBezirk.SCHLUESSEL = bb.BUCHUNGSBLATTBEZIRK)
							LEFT OUTER JOIN AX_BLATTART_TBD tbdBlattart ON(tbdBlattart.SHORT_VALUE = bb.BLATTART)
							WHERE me.bsid = '{BSID}'
						]]></Sql>

						<BindTo>data_gvBuchungsblaetter</BindTo>

						<HeaderText From="buchungsblattkennzeichen" To="Buchungsblatt"/>
						<HeaderText From="bb_bezirk_schl_value" To="Buchungsblattbezirk"/>
						<HeaderText From="buchungsblattnummermitbuch" To="Buchungsblattnummer"/>
						<HeaderText From="blattart_value" To="Blattart"/>
					</Bindings>

					<ItemTemplate>ItemTemplates\AX_FLURSTUECK\AX_FLURSTUECK_V_BUCHUNGSBLATT_FS</ItemTemplate>
				</Panel>

				<!-- Eigentümer nach Buchungsblättern - V_EIGENTUEMER_FS -->
				<Panel>
					<Caption>Eigentümer nach Buchungsblättern</Caption>
					<Authorisation>AX_PERSON</Authorisation>
					<HideIfQueryIsEmpty>true</HideIfQueryIsEmpty>
					<Query>
						<Name>V_EIGENTUEMER_FS</Name>
						<Parent>AX_FLURSTUECK</Parent>
